# Generated by Django 5.0.3 on 2024-04-08 14:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(choices=[('BMW', 'Bmw'), ('Mercedes', 'Mercedes'), ('Volkswagen', 'Vw'), ('Peugeot', 'Peugeot'), ('OPEL', 'Opel'), ('Other', 'Other')], max_length=10)),
                ('engine_type', models.CharField(choices=[('Дизел', 'Diesel'), ('Бензин', 'Petrol'), ('Хибрид', 'Hybrid')], max_length=10)),
                ('year', models.PositiveIntegerField()),
                ('vin', models.CharField(error_messages={'unique': 'Този VIN номер вече се използва! Опитайте отново!'}, max_length=17, unique=True, validators=[django.core.validators.MinLengthValidator(17)])),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
